// Code generated by protoc-gen-go-futu. DO NOT EDIT.

package keepalive

import (
	"google.golang.org/protobuf/proto"
	"errors"
)

type ResponseChan struct {
	ch chan *Response
}

func NewResponseChan() *ResponseChan {
	return &ResponseChan{
		ch: make(chan *Response),
	}
}

func (ch *ResponseChan) Send(b []byte) error {
	var resp Response
	if err := proto.Unmarshal(b, &resp); err != nil {
		return err
	}
	ch.ch <- &resp
	return nil
}

func (ch *ResponseChan) Close() {
	close(ch.ch)
}

func (ch *ResponseChan) Response() (*S2C, error) {
	resp := <-ch.ch
	if resp.GetRetType() != 0 {
		return nil, errors.New(resp.GetRetMsg())
	}
	return resp.S2C, nil
}

func (ch *ResponseChan) Channel() chan *Response {
	return ch.ch
}
